#
# This file was generated by autocomplete-generator https://gitlab.com/philippecaphin/autocomplete-generator
#

# This is the function that will be called when we press TAB.
#
# Its purpose is to examine the current command line (as represented by the
# array COMP_WORDS) and to determine what the autocomplete should reply through
# the array COMPREPLY.
#
# This function is organized with subroutines who  are responsible for setting
# the 'ssmuse_sh_compreply_candidates' variable.
#
# The compgen then filters out the candidates that don't begin with the word we are
# completing. In this case, if '--' is one of the words, we set empty candidates,
# otherwise, we look at the previous word and delegate # to candidate-setting functions
__complete_ssmuse_sh() {

	COMPREPLY=()

	# We use the current word to filter out suggestions
	local cur="${COMP_WORDS[COMP_CWORD]}"
	local ssmuse_sh_compreply_candidates=""
	__suggest_ssmuse_sh_compreply_candidates >> ~/log.txt 2>&1


	# Compgen: takes the list of candidates and selects those matching ${cur}.
	# Once COMPREPLY is set, the shell does the rest.
	COMPREPLY=( $(compgen -W "${ssmuse_sh_compreply_candidates}" -- ${cur}))
	echo "COMPREPLY = ${COMPREPLY[@]}" >> ~/log.txt

	return 0
}

__suggest_ssmuse_sh_compreply_candidates(){
	# We use the current word to decide what to do
	local cur="${COMP_WORDS[COMP_CWORD]}"
	if __ssmuse_sh_dash_dash_in_words ; then
		return
	fi

	option=$(__ssmuse_sh_get_current_option)
	if [[ "$option" != "" ]] ; then
		__suggest_ssmuse_sh_args_for_option ${option}
	else
		# Suggest from filesystem if current word doesn't start with '-'
		# if ! [[ "$cur" = -* ]] ; then
		# 	return
		# fi
		__suggest_ssmuse_sh_options
	fi
}

__ssmuse_sh_dash_dash_in_words(){
	for ((i=0;i<COMP_CWORD-1;i++)) ; do
		w=${COMP_WORDS[$i]}
		if [[ "$w" == "--" ]] ; then
			return 0
		fi
	done
	return 1
}

__ssmuse_sh_get_current_option(){
	# The word before that
	local prev="${COMP_WORDS[COMP_CWORD-1]}"
	if [[ "$prev" == -* ]] ; then
		echo "$prev"
	fi
}

__suggest_ssmuse_sh_options(){
	ssmuse_sh_compreply_candidates=" -d"
}

__suggest_ssmuse_sh_args_for_option(){
	case "$1" in
		-d) __suggest_ssmuse_sh_key_d_values ;;
	esac
}

__suggest_ssmuse_sh_key_d_values(){
    ssmuse_sh_compreply_candidates="$(env -i ls ~phc001/site4/ssm | sed 's/^/\/home\/phc001\/site4\/ssm\//')"
}

p.ssmuse-sh(){
    . ssmuse-sh
}

complete -o default -F __complete_ssmuse_sh ssmuse-sh 'p.ssmuse-sh'
