#!/bin/sh
# echo ".profile.d/default/dist.post START"
#----- Override EER environment variables
export EER_USERREP=
export SSM_DEV=/fs/cetus3/fs3/cmd/s/afsm/pca/ssm/
export EXT_SRC_PATH=/users/dor/afsr/ops/Links/devfs/Archive 
export EXT_LIB_PATH=/users/dor/afsr/ops/Links/devfs/Lib
export EER_GRIDF=/home/binops/afse/par/links/meteo/castor

export SSCP_SSH_OPTIONS="-F /dev/null"
# echo ".profile.d/default/dist.post END"
