#!/bin/bash
pushd /tmp

   mkdir -p phil
   mkdir -p phil/.cache

   pushd phil

   if ! [ -e SPI ] ; then
      git clone ~/Documents/GitHub/SPI_PHIL SPI
   fi

   if ! [ -e emacs.d ] ; then
      git clone https://github.com/syl20bnr/spacemacs emacs.d
   fi

   if ! [ -e emacs-26.1.tar.gz ] ; then
      wget http://gnu.mirror.iweb.com/emacs/emacs-26.1.tar.gz
      tar -zxvf emacs-26.1.tar.gz
   popd

popd
