#!/bin/bash
pushd /tmp

   mkdir -p phil
   mkdir -p phil/.cache

   pushd phil

   if ! [ -e SPI ] ; then
      git clone ~/Documents/GitHub/SPI_PHIL SPI
   fi

   if ! [ -e emacs-26.1 ] ; then
      if ! [ -e emacs-26.1.tar.gz ] ; then
         wget http://gnu.mirror.iweb.com/emacs/emacs-26.1.tar.gz
      fi
      tar -zxvf emacs-26.1.tar.gz
      cd emacs-26.1
      ./autogen.sh
      ./configure --with-x-toolkit=no --with-xpm=no --with-gif=no --prefix=$HOME/.local/opt
      make -j 32
      cd ..
   fi

   kcg=kcachegrind-0.7.4
   if ! [ -e $kcg ] ; then
      if ! [ -e ${kcg}.tar.gz ] ; then
         wget http://kcachegrind.sourceforge.net/kcachegrind-0.7.4.tar.gz
      fi
      tar -zxvf ${kcg}.tar.gz
      (cd $kcg ; mkdir build ; cd build ; qmake ../qcg.pro ; make -j 32)
   fi
   popd

popd
