#!/bin/bash

echo "$(date) : brew $@" >> ~/.philconfig/brew_log.txt

brew $@

if $? ; then
	echo "                               >> Success" >> ~/.philconfig/brew_log.txt
else
	echo "                               >> Failed" >> ~/.philconfig/brew_log.txt
fi
