#!/bin/sh

set LD_LIBRARY_PATH "$HOME/.local/openblas/lib:$LD_LIBRARY_PATH:/usr/local/cuda/lib"

set THEANO_FLAGS device=cpu,optimizer=fast_run,exception_verbosity=high

set DYLD_LIBRARY_PATH $HOME/.local/openblas/lib:/Developer/NVIDIA/CUDA-8.0/lib:$DYLD_LIBRARY_PATH

# Locally installed programs
set PATH "$PATH
$HOME/.local/bin
$HOME/Documents/GitHub/utils/bin
/Developer/NVIDIA/CUDA-8.0/bin
/Library/Frameworks/Python.framework/Versions/3.5/bin
/usr/local/openclcc/bin
/usr/bin
/usr/lib64/openmpi/bin
/usr/local/opt/apr/bin"

export PATH
