#!/bin/sh
#
# Allows me to open my rcfile quickly and reload it quickly
if [[ "$SHELL" == zsh ]] && [ -z $BASH ] ; then
	rcfile=$HOME/.zshrc
else
	rcfile=$HOME/.bashrc
fi

alias lprofile="source $rcfile"

# If I skip the space with cd ..
alias cd..='cd ..'

# Make gitk always show all branches
alias gitk="gitk --all --select-commit=HEAD &"

alias gitroot='cd $(git root)'

# Quick aliases for valgrind
alias vgrindtotmem="valgrind --tool=massif --stacks=yes"
alias vgrind="valgrind --tool=memcheck --leak-check=yes"

# Make grep show colors and line numbers
alias grep='grep --color=auto -n'

# Make less accept colored input
alias less='less -R'

# Add PWD to path for current session.  Useful for recompiling and
# running executables without always writing './'
alias pathpwd='export PATH=$PWD:$PATH'

# Aliases for quick directories:
alias github='cd ~/Documents/GitHub'

source $CONFIG_DIR/github-aliases
alias new-repo='source new-repo.sh'

# Opens the master PDF documenation for ATMega324PA assuming it is
# at this path.
alias docatmel='open ~/Documents/docatmel.pdf 2>/dev/null &'

# OS specific commands
if [ $(uname) = Linux ]; then
	# echo "   Loading Linux commands" 1>&2
	# ls always shows color
	alias ls='ls --color'
	alias open='gio open'
  # See disk usage: lists the sizes of the folders in the current
  # directory and sorts them by size
  alias dusage='du --max-depth=1 -h | sort -h'
elif [ $(uname) = Darwin ]; then
	# echo "   Loading Darwin commands" 1>&2
	# ls always shows color
	alias ls='ls -G'
	# Redefine dusage command for MAC
	alias dusage='du -d 1 -h | sort -h'
fi

alias setenv='source ./setenv'
alias my-ip='curl ipinfo.io/ip'
alias show-log='cat ~/Documents/GitHub/flask_test/nohup.out'
alias leelaz-cmd='leelaz -w /usr/local/bin/leelaz-weights.txt'
alias tk='tmux kill-window'
alias tkk='tmux kill-session'
alias ts='tmux source-file launch-everything-home.tmux'
alias play='mpv --quiet -vo caca'
alias sabaki='/Applications/Sabaki.app/Contents/MacOS/Sabaki'
alias callgrind='valgrind --tool=callgrind'
alias MAKE='make clean >/dev/null 2>&1 ; make'
alias sql_date='date +%Y-%m-%d\ %H:%M:%S'
alias datestamp='date "+%Y-%m-%d_%H%M"'
