#!/bin/sh
#
# Allows me to open my rcfile quickly and reload it quickly
if [[ "$SHELL" == zsh ]] ; then
	rcfile=$HOME/.zshrc
else
	rcfile=$HOME/.bashrc
fi
alias profile='vim $rcfile $HOME/.functions $HOME/.general-aliases $HOME/.envvars && source $rcfile'
alias lprofile="source $rcfile"

# If I skip the space with cd ..
alias cd..='cd ..'

# See disk usage: lists the sizes of the folders in the current
# directory and sorts them by size
alias dusage='du --max-depth=1 | sort -n'

# Make gitk always show all branches
alias gitk="gitk --all --select-commit=HEAD &"

alias gitroot='cd $(git root)'

# Quick aliases for valgrind
alias vgrindtotmem="valgrind --tool=massif --stacks=yes"
alias vgrind="valgrind --tool=memcheck --leak-check=yes"

# Make grep show colors and line numbers
alias grep='grep --color=auto -n'

# Make less accept colored input
alias less='less -R'

# Add PWD to path for current session.  Useful for recompiling and
# running executables without always writing './'
alias pathpwd='export PATH=$PWD:$PATH'

# Aliases for quick directories:
alias github='cd ~/Documents/GitHub'

source ~/.github-aliases
alias new-repo='source new-repo.sh'

# Opens the master PDF documenation for ATMega324PA assuming it is
# at this path.
alias docatmel='open ~/Documents/docatmel.pdf 2>/dev/null &'

# OS specific commands
if [ $(uname) = Linux ]; then
	# echo "   Loading Linux commands" 1>&2
	# ls always shows color
	alias ls='ls --color'
	alias open='gio open'
elif [ $(uname) = Darwin ]; then
	# echo "   Loading Darwin commands" 1>&2
	# ls always shows color
	alias ls='ls -G'
	# Redefine dusage command for MAC
	alias dusage='du -d 1 | sort -n'
fi

accents="âàäêèëéîïôöûùüÿçÂÀÄÊÈËÉÎÏÔÖÛÙÜŸÇ¨"
no_accents="aaaeeeeiioouuuycAAAEEEEIIOOUUUYC "
alias remove-accents="tr '$accents' '$no_accents'"
alias setenv='source ./setenv'
alias my-ip='curl ipinfo.io/ip'
alias show-log='cat ~/Documents/GitHub/flask_test/nohup.out'
alias leelaz-cmd='leelaz -w /usr/local/bin/leelaz-weights.txt'
alias tk='tmux kill-window'
alias ts='tmux source-file launch-everything-home.tmux'
alias play='mpv --quiet -vo caca'
alias sabaki='/Applications/Sabaki.app/Contents/MacOS/Sabaki'

open_cmc() {
   to_open=$1
   nohup dolphin $to_open > /dev/null 2>&1 &
}
if at_cmc ; then
    SPI_DIR=~/Documents/GitHub/SPI
    alias gospi='cd $SPI_DIR'
    alias gospic='cd $SPI_DIR/LibTkGL/TclGeoEER/generic'
    alias quota='ssh lightning quota'
    alias git='/ssm/net/cmoi/apps/git/20150526/ubuntu-14.04-amd64-64/bin/git'
    alias gitk='/ssm/net/cmoi/apps/git/20150526/ubuntu-14.04-amd64-64/bin/gitk --all &'
    alias gg='git gui &'
    alias tmuxspi='tmux new-session \; source-file ~/spi-dev.tmux'
    alias tclsh='/ssm/net/cmoe/apps/libSPI_7.12.2_ubuntu-14.04-amd64-64/TCL/bin/tclsh8.6'
    alias wish='/ssm/net/isst/maestro/1.4.3-rc4/linux26-x86-64/bin/wish'
    alias runxp='rdesktop -g 1280x720 eccmcwts3 -d ECQUEBEC -u CarphinP'
    alias open=open_cmc
    alias make=pmake
fi
