#!/bin/sh
#
# Allows me to open my rcfile quickly and reload it quickly
if [[ "$SHELL" == zsh ]] && [ -z $BASH ] ; then
	rcfile=$HOME/.zshrc
else
	rcfile=$HOME/.bashrc
fi

alias lprofile="source $rcfile"

# If I skip the space with cd ..
alias cd..='cd ..'

# See disk usage: lists the sizes of the folders in the current
# directory and sorts them by size
alias dusage='du --max-depth=1 | sort -n'

# Make gitk always show all branches
alias gitk="gitk --all --select-commit=HEAD &"

alias gitroot='cd $(git root)'

# Quick aliases for valgrind
alias vgrindtotmem="valgrind --tool=massif --stacks=yes"
alias vgrind="valgrind --tool=memcheck --leak-check=yes"

# Make grep show colors and line numbers
alias grep='grep --color=auto -n'

# Make less accept colored input
alias less='less -R'

# Add PWD to path for current session.  Useful for recompiling and
# running executables without always writing './'
alias pathpwd='export PATH=$PWD:$PATH'

# Aliases for quick directories:
alias github='cd ~/Documents/GitHub'

source ~/.github-aliases
alias new-repo='source new-repo.sh'

# Opens the master PDF documenation for ATMega324PA assuming it is
# at this path.
alias docatmel='open ~/Documents/docatmel.pdf 2>/dev/null &'

# OS specific commands
if [ $(uname) = Linux ]; then
	# echo "   Loading Linux commands" 1>&2
	# ls always shows color
	alias ls='ls --color'
	alias open='gio open'
elif [ $(uname) = Darwin ]; then
	# echo "   Loading Darwin commands" 1>&2
	# ls always shows color
	alias ls='ls -G'
	# Redefine dusage command for MAC
	alias dusage='du -d 1 | sort -n'
fi

accents="âàäêèëéîïôöûùüÿçÂÀÄÊÈËÉÎÏÔÖÛÙÜŸÇ¨"
no_accents="aaaeeeeiioouuuycAAAEEEEIIOOUUUYC "
alias remove-accents="tr '$accents' '$no_accents'"
alias setenv='source ./setenv'
alias my-ip='curl ipinfo.io/ip'
alias show-log='cat ~/Documents/GitHub/flask_test/nohup.out'
alias leelaz-cmd='leelaz -w /usr/local/bin/leelaz-weights.txt'
alias tk='tmux kill-window'
alias tkk='tmux kill-session'
alias ts='tmux source-file launch-everything-home.tmux'
alias play='mpv --quiet -vo caca'
alias sabaki='/Applications/Sabaki.app/Contents/MacOS/Sabaki'
alias callgrind='valgrind --tool=callgrind'
alias MAKE='make clean >/dev/null 2>&1 ; make'

open_cmc() {
   to_open=$1
   nohup dolphin $to_open > /dev/null 2>&1 &
}
export NOTES_DIR="~/Dropbox/Notes/Notes_BUCKET"
if at_cmc ; then
    export SPI_DIR="~/Documents/GitHub/SPI_PHIL"
    export SPOOKI_DIR="~/Documents/GitHub/SPOOKI_PHIL"
    export SPOOKI_TMPDIR="/tmp/$(whoami)/$$"
    CMC_NOTES_DIR="~/Dropbox/Notes/CMC/"
    alias gospi='cd $SPI_DIR'
    alias gospic="cd $SPI_DIR/LibTkGL/TclGeoEER/generic"
    alias gospit="cd $SPI_DIR/LibTkGL/TclGeoEER/MetObsTest"
    alias gospoo="cd $SPOOKI_DIR"
    alias makespi='(cd $SPI_DIR/LibTkGL/ ; ./makeit -spi)'
    alias quota='ssh lightning quota'
    alias git='/ssm/net/cmoi/apps/git/20150526/ubuntu-14.04-amd64-64/bin/git'
    alias gitk='/ssm/net/cmoi/apps/git/20150526/ubuntu-14.04-amd64-64/bin/gitk --all &'
    alias gg='git gui &'
    alias tmuxspi='tmux new-session \; source-file ~/spi-dev.tmux'
    alias tclsh='/ssm/net/cmoe/apps/libSPI_7.12.2_ubuntu-14.04-amd64-64/TCL/bin/tclsh8.6'
    alias wish='/ssm/net/isst/maestro/1.4.3-rc4/linux26-x86-64/bin/wish'
    alias runxp='nohup rdesktop -g 840x525 eccmcwts3 -d ECQUEBEC -u CarphinP &'
    alias runxp-big='nohup rdesktop -g 1280x950 eccmcwts3 -d ECQUEBEC -u CarphinP &'
    alias open=open_cmc
    fs3=/fs/cetus3/fs3/cmd/s/afsm/pca
    alias fs3='cd $fs3'
    alias spireconf='cd $SPI_DIR/LibTkGL/TclGeoEER ; /usr/bin/autoconf2.50 || echo "spireconf failed" ; cd - >/dev/null'
    alias bash_back="sed 's/\\(exec zsh\\)/# \\1/' < ~/.bashrc > ~/.philconfig/brc ; mv ~/.philconfig/brc ~/.philconfig/bashrc"
    alias zsh_back="sed 's/\\(# \\)*\\(exec zsh\\)/\\2/' < ~/.bashrc > ~/.philconfig/brc ; mv ~/.philconfig/brc ~/.philconfig/bashrc"

    # Here it is important that there be forward slashes at the end.  This
    # changes what rsync will do.  To be sure in case I forget and remove
    # the forward slashes in the variable definitions, it is better to add
    # them here and not wonder if the variable has them.
    alias push_cmc_notes="rsync -av --cvs-exclude $CMC_NOTES_DIR/ house:$CMC_NOTES_DIR/"
    alias pull_cmc_notes="rsync -av --cvs-exclude house:$CMC_NOTES_DIR/ $CMC_NOTES_DIR/"

    # No push_notes because I want to be really sure that I don't delete anything important.
    alias pull_notes="rsync -av --cvs-exclude house:$NOTES_DIR/ $NOTES_DIR/"
    alias push_notes="rsync -av --cvs-exclude $NOTES_DIR/ house:$NOTES_DIR/"

    spi_path=/users/dor/afsm/pca/Documents/GitHub/SPI_PHIL/eer_SPI/
    alias spi_beta='export SPI_LIB=$SSM_DEV/workspace/libSPI_7.12.2_${ORDENV_PLAT}; export SPI_PATH=$spi_path'
    alias spi++='spi_beta; $SPI_PATH/bin/SPI'
    alias emacs='/usr/bin/emacs -q'
    alias spacemacs=~/.local/bin/emacs-26.1
fi
alias sql_date='date +%Y-%m-%d\ %H:%M:%S'
