#!/bin/sh
alias 47051='cd ~/Documents/GitHub/INF4705_TP1'
alias 8480='cd ~/Documents/GitHub/INF8480_TP3'
alias 8405='cd ~/Documents/GitHub/INF8405_TP1'
alias 47052='cd ~/Documents/GitHub/INF4705_TP2'
alias 47053='cd ~/Documents/GitHub/INF4705_TP3'
alias 82252='cd ~/Documents/GitHub/INF8225_TP2'
alias 82253='cd ~/Documents/GitHub/INF8225_TP3'
alias 8225p='cd ~/Documents/GitHub/INF8225_projet'
alias 1995='cd ~/Documents/GitHub/INF1995_PRJ'
alias c1995='cd ~/Documents/GitHub/INF1995_1HIV2017_TP7'
alias audio='cd ~/Documents/GitHub/Projet_Audiologie/'
alias react='cd ~/Documents/GitHub/react_test'
alias tests='cd ~/Documents/GitHub/tests'


alias 8601='cd ~/Documents/GitHub/INF8601_TP1'

alias 86011='cd ~/Documents/GitHub/INF8601_TP1'


alias utils='cd ~/Documents/GitHub/utils'
alias igo='cd ~/Documents/GitHub/go_sgf_to_igo_latex'
alias syspara='cd ~/Documents/GitHub/INF8601_TP3'
alias chess='cd ~/Documents/GitHub/chess'
