#!/bin/sh
alias 47051='cd ~/Documents/GitHub/INF4705_TP1'
alias 47052='cd ~/Documents/GitHub/INF4705_TP2'
alias 47053='cd ~/Documents/GitHub/INF4705_TP3'
alias 82252='cd ~/Documents/GitHub/INF8225_TP2'
alias 82253='cd ~/Documents/GitHub/INF8225_TP3'
alias 8225p='cd ~/Documents/GitHub/INF8225_projet'
alias 1995='cd ~/Documents/GitHub/INF1995_PRJ'
alias c1995='cd ~/Documents/GitHub/INF1995_1HIV2017_TP7'
alias audio='cd ~/Documents/GitHub/Projet_Audiologie/'
alias cnb='cd ~/Documents/GitHub/cock-n-balls'





alias utils='cd ~/Documents/GitHub/utils'
