alias sci='ssh -CX nil000@sci-eccc-in.science.gc.ca'
alias sops='ssh -CX smco610@sci-eccc-in.science.gc.ca'
alias spar='ssh -CX smco601@sci-eccc-in.science.gc.ca'
alias seer='ssh -CX smco600@sci-eccc-in.science.gc.ca'
alias ppp1='ssh -CX -t nil000@sci-eccc-in.science.gc.ca ssh -CX nil000@eccc-ppp1'
alias sedi='ssh -CX gauthierjp@nii-edigraf-dev.wul.qc.ec.gc.ca'

alias rq='/home/binops/afsf/ops/S/TCL/RapQuart/Rap_Quart.tcl'
alias tdev='ssh -YX $USER@terascan-dev "export TZ=GMT; . /opt/terascan/etc/tscan.bash_profile; tvis -true -windows 15"'
alias tops='ssh -YX $USER@terascan-op  "export TZ=GMT; . /opt/terascan/etc/tscan.bash_profile; tvis -true -windows 15"'

alias hi='history 100'
alias psu='ps -u $USER'
alias psp='ps -o pid,ppid,cmd'
alias rm='rm -i'
alias sshx='ssh -CX'
alias setjp='set -o emacs; export EDITOR=kate; export DISPLAY=vlad:0.0'
alias setfont='xset +fp /users/dor/afsr/002/tmp/75dpi'
alias xp='rdesktop ECCMCWTS3 -u gauthierjp -d eccmc -g 1918x1130'
alias mp4='\rm out.mp4; cat *.jpg | avconv -f image2pipe -r 10 -c:v mjpeg -i - -map 0 -c:v mpeg4 -r 20 -pix_fmt yuv420p -qscale 1 out.mp4'
alias asep='ssh afsynav@asep-dev1'
