#!/bin/zsh

if [[ "$TERM" == "dumb" ]] ; then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  if whence -w precmd >/dev/null; then
      unfunction precmd
  fi
  if whence -w preexec >/dev/null; then
      unfunction preexec
  fi
  PS1='$ '
  return
fi


# From https://fish-users.narkive.com/qmgw3G37/ls-colors-with-fish
# set -Ux LSCOLORS Exfxcxdxbxegedabagacad
# From https://apple.stackexchange.com/a/33679
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

source ~/.philconfig/environment/path.sh

function zshrc_interactive(){
    autoload -U compinit ; compinit
    alias n='nnn -dhQex'
    for f in $(env -i ls $STOW_DIR/etc/zsh_completion.d) ; do
        source $STOW_DIR/etc/zsh_completion.d/$f
    done
    source /opt/homebrew/opt/modules/init/zsh
    module load use.own
}

if [[ "$-" == *i* ]] ; then
    if ! [ -e ~/.normal_mode ] ; then
        exec fish $@
    fi
    zshrc_interactive
fi
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/Users/pcarphin/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/Users/pcarphin/miniforge3/etc/profile.d/conda.sh" ]; then
#         . "/Users/pcarphin/miniforge3/etc/profile.d/conda.sh"
#     else
#         export PATH="/Users/pcarphin/miniforge3/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<
