#!/bin/bash

# echo "~/.profile START"
# source ~/.ord-functions-phil.sh
# if [ -e $HOME/site4_phil/tmpdir ] ; then
#    export TMPDIR=~/site4_phil/tmpdir
# fi

eval_and_print(){
   echo $(tput setaf 2)$1$(tput sgr 0)
   eval $1
}

setup_ordenv_ppp4(){
   ### environment setup - start
   export ORDENV_SITE_PROFILE=20190617-test
   export ORDENV_COMM_PROFILE=eccc/20190617-test
   export ORDENV_GROUP_PROFILE=eccc/cmc/1.7-beta.3
   . /fs/ssm/main/env/ordenv-boot-20190617-test.sh

   ### environment setup - env
   #export EC_SHORTCUT_PATH=/fs/ssm:/fs/ssm/eccc:/fs/ssm/eccc/mrd
   export EC_ATOMIC_PROFILE_VERSION=1.7-beta.3
}

setup_ordenv_ppp4_17beta4(){
   # ref /fs/ssm/eccc/mrd/ordenv/profile/1.7-beta.4
   ### environment setup - start
   export ORDENV_SITE_PROFILE=20190617-test
   export ORDENV_COMM_PROFILE=eccc/20190617-test
   export ORDENV_GROUP_PROFILE=eccc/cmc/1.7-beta.4
   . /fs/ssm/main/env/ordenv-boot-20190617-test.sh

   ### environment setup - env
   #export EC_SHORTCUT_PATH=/fs/ssm:/fs/ssm/eccc:/fs/ssm/eccc/mrd
   export EC_ATOMIC_PROFILE_VERSION=1.7-beta.4
}

poutine_science(){
   echo $(tput setab 2)Starting ordenv$(tput sgr 0)
   eval_and_print "export ORDENV_SITE_PROFILE=20180130"
   eval_and_print "export ORDENV_GROUP_PROFILE=eccc/cmc/1.6"
   eval_and_print "export ORDENV_COMM_PROFILE=eccc/20180130"
   eval_and_print "source /fs/ssm/main/env/ordenv-boot-20180430.sh"
   ### environment setup - env
   eval_and_print "export EC_ATOMIC_PROFILE_VERSION=1.6"
   echo $(tput setab 2)END Ordenv stuff$(tput sgr 0)
}

hot_chicken_pyspooki(){
    echo "$(tput setab 2)Sourcing things for BUILDING PySpooki$(tput sgr 0)"
    eval_and_print "export PHIL_PYSPOOKI_CONTAINER=~/hall1_phil/spooki/"
    eval_and_print "export PHIL_PYSPOOKI_BUILD_DIR=$PHIL_PYSPOOKI_CONTAINER/build"
    eval_and_print "export PHIL_PYSPOOKI_SRC_DIR=~/workspace/spooki/"
    eval_and_print "source $PHIL_PYSPOOKI_SRC_DIR/SETUP_ubuntu-14.04-amd64-64"
    eval_and_print "export SPOOKI_TMPDIR=$TMPDIR/spooki"
    eval_and_print "mkdir -p $SPOOKI_TMPDIR"
    eval_and_print "source ~/hall1_phil/spooki/build/export_env_var"

    # . s.ssmuse.dot ENV/d/modelutils/modelutils_1.3.2
    # . ssmuse-sh -d hpcs/201402/00-test/base -d hpcs/201402/00-test/intel13sp1 -d rpn/env/00-test
    echo "$(tput setab 2)END pyspooki stuff$(tput sgr 0)"
}

if [[ -e ~/.je_suis_ppp1_ou_ppp2 ]] ; then
   # Je suis sur ppp1 ou ppp2
   if [[ $(hostname) != eccc* ]] ; then
      # Je suis sur un compute node de ppp1 ou ppp2
      # echo "$(tput setab 2)Doing CMC science network specific stuff$(tput sgr 0)"
      # poutine_science
      # hot_chicken_pyspooki
      # echo "$(tput setab 2)Done CMC science network specific stuff$(tput sgr 0)"
      true
   fi
fi

if [[ -e ~/.je_suis_ppp3_ou_ppp4 ]] ; then
   setup_ordenv_ppp34
fi

# if [[ -e ~/je_suis_ppp4 ]] ; then
#    source ~/workspace/spooki/spooki_ppp4_dev_setup.sh
# fi
# setup_ordenv_ppp4_17beta4
# source ~/workspace/spooki/SETUP_ubuntu-18.04-amd64-64

setup_ordenv_ppp34(){
   export ORDENV_SITE_PROFILE=20190814
   export ORDENV_COMM_PROFILE=eccc/20191002
   export ORDENV_GROUP_PROFILE=eccc/cmc/1.7
   . /fs/ssm/main/env/ordenv-boot-20190814.sh
}



# echo "~/.profile END"
