#!/bin/bash

source ~/.philconfig/shell_rc_common
source ~/.philconfig/shell_rc.bash
source ~/.philconfig/shell_rc.bash.home
source ~/.philconfig/shell_lib/functions.sh

export PS4='+ \033[35m${BASH_SOURCE[0]}\033[36m:\033[1;37m${FUNCNAME:+${FUNANAME[0]}}\033[22;36m:\033[32m${LINENO}\033[0m -- '


cat ~/a.txt >&2
