#!/bin/bash
# echo ".bash_profile START" >&2
export PHILCONFIG=$HOME/.philconfig

source $PHILCONFIG/FILES/initutils

source ~/.philconfig/FILES/envvars

source ~/.bashrc

export PHILRC_BASH_PROFILE="bash_profile_loaded_at_$(date "+%Y-%m-%d_%H%M")"
# echo ".bash_profile END" >&2
