#!/bin/bash

# echo "~/.profile START"

poutine_science(){
   export ORDENV_SITE_PROFILE=20180130
   export ORDENV_GROUP_PROFILE=eccc/cmc/1.5
   export ORDENV_COMM_PROFILE=eccc/20180130
   source /fs/ssm/main/env/ordenv-boot-20170103.sh
   ### environment setup - env
   export EC_ATOMIC_PROFILE_VERSION=1.5-beta
}

hot_chicken_pyspooki(){
    export PHIL_PYSPOOKI_CONTAINER=~/hall1_phil/spooki/
    export PHIL_PYSPOOKI_BUILD_DIR=$PHIL_PYSPOOKI_CONTAINER/build
    echo "$(tput setab 2)Sourcing things for PySpooki$(tput sgr 0)"
    echo "$(tput setaf 2)Sourcing $PHIL_PYSPOOKI_CONTAINER/SETUP_ubuntu-14.04-amd64-64$(tput sgr 0)"
    source $PHIL_PYSPOOKI_CONTAINER/SETUP_ubuntu-14.04-amd64-64
    echo "$(tput setab 2)END pyspooki stuff$(tput sgr 0)"
}

if [[ $(cmc_network) == "science" ]] ; then
   poutine_science
   hot_chicken_pyspooki
fi

# echo "~/.profile END"
