#!/bin/bash

# echo "~/.profile START"
source $PHILCONFIG/FILES/initutils
source $PHILCONFIG/FILES/functions

eval_and_print(){
   echo $(tput setaf 2)$1$(tput sgr 0)
   eval $1
}

setup_ordenv(){
   echo $(tput setab 2)Starting ordenv$(tput sgr 0)
   eval_and_print "export ORDENV_SITE_PROFILE=20180130"
   eval_and_print "export ORDENV_GROUP_PROFILE=eccc/cmc/1.6"
   eval_and_print "export ORDENV_COMM_PROFILE=eccc/20180130"
   eval_and_print "source /fs/ssm/main/env/ordenv-boot-20180430.sh"
   ### environment setup - env
   eval_and_print "export EC_ATOMIC_PROFILE_VERSION=1.6"
   echo $(tput setab 2)END Ordenv stuff$(tput sgr 0)
}

if [[ $(cmc_network) == "science" ]] ; then
   if [[ $(hostname) != eccc* ]] ; then
      setup_ordenv
      source ~/workspace/spooki/SETUP_ubuntu-14.04-amd64-64
   else
      # setup_ordenv
      export CXX=/usr/bin/g++
      true
   fi
fi

# echo "~/.profile END"
