#!/bin/sh
# echo ".envvars START"

# echo "initial LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
MY_LD_LIBRARY_PATH=$MY_LD_LIBRARY_PATH:$HOME/.local/lib
MY_LD_LIBRARY_PATH=$MY_LD_LIBRARY_PATH:$HOME/.local/openblas/lib/
MY_LD_LIBRARY_PATH=$MY_LD_LIBRARY_PATH:$HOME/.local/libgit2/lib
MY_LD_LIBRARY_PATH=$MY_LD_LIBRARY_PATH:/usr/local/cuda/lib
export LD_LIBRARY_PATH="$MY_LD_LIBRARY_PATH:$LD_LIBRARY_PATH"

THEANO_FLAGS=\
            device=cpu,\
            optimizer=fast_run,\
            exception_verbosity=high

# echo "initial DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH"
MY_DYLD_LIBRARY_PATH=$MY_DYLD_LIBRARY_PATH:$HOME/.local/lib
MY_DYLD_LIBRARY_PATH=$MY_DYLD_LIBRARY_PATH:$HOME/.local/openblas/lib
MY_DYLD_LIBRARY_PATH=$MY_DYLD_LIBRARY_PATH:/Developer/NVIDIA/CUDA-8.0/lib
export DYLD_LIBRARY_PATH=$MY_DYLD_LIBRARY_PATH:$DYLD_LIBRARY_PATH


# echo "initial path = $PATH"
MY_PATH=$HOME/.local/bin                                                       # Locally installed programs
MY_PATH=$MY_PATH:$HOME/Documents/GitHub/utils/bin                              # Utility scripts that I keep track of with git.
MY_PATH=$MY_PATH:/Developer/NVIDIA/CUDA-8.0/bin                                # Add cuda stuff to path
MY_PATH=$MY_PATH:/Library/Frameworks/Python.framework/Versions/3.5/bin         # Setting PATH for Python 3.5 on OSX
MY_PATH=$MY_PATH:/usr/lib64/openmpi/bin                                        # For systemes paralleles
MY_PATH=$MY_PATH:/usr/local/openclcc/bin                                       # For systemes paralleles
MY_PATH=$MY_PATH:/usr/local/opt/apr/bin                                        # Added this so that apr-1-config could be found on my mac on Feb 7th 2018.
MY_PATH=$MY_PATH:$HOME/Library/Python/2.7/bin                                  # For Amazon AWS
export PATH=$MY_PATH:$PATH

export CDPATH=".:$HOME":$HOME/Documents:$HOME/Documents/GitHub

LESS="$LESS -FX"                                                               # For git log to display without paging if output fits on one screen
LESS="$LESS -R"                                                                # For less to have color
export LESS

export LANG=en_US.UTF-8
export LC_COLLATE=C                                                            # Makes ls sortint case sensitive
export EDITOR=vim                                                              # Set editor as vim for most things
export FCEDIT=vim

#if in tmux, export this I forget why
! [ -z "$TMUX" ] && export TERM=xterm-256color

export NOTES_DIR="~/Dropbox/Notes/Notes_BUCKET"

# echo ".envvars END"
